In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
arreglo_np = np.array([1,2,3])

In [4]:
type(arreglo_np)

numpy.ndarray

In [5]:
tupla_np = np.array((1,2,3,4))

In [6]:
type(tupla_np)

numpy.ndarray

In [7]:
np.zeros((1))

array([0.])

In [8]:
np.zeros((5))

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
np.zeros([5,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
np.zeros([5,2,3])

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
np.ones((1))

array([1.])

In [14]:
np.ones((1,2))

array([[1., 1.]])

In [15]:
np.ones((5,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [16]:
np.empty((5,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [17]:
np.empty((5,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [18]:
np.empty((3,4,5))

array([[[2.32621426e-314, 2.18510800e-314, 2.32621420e-314,
         2.18510800e-314, 2.32621362e-314],
        [2.18510800e-314, 2.32621359e-314, 2.18510800e-314,
         2.33063148e-314, 2.18477523e-314],
        [2.18510800e-314, 2.33680319e-314, 2.18480525e-314,
         2.33063145e-314, 2.18510800e-314],
        [2.22177706e-314, 2.18480525e-314, 2.33063112e-314,
         2.18510800e-314, 2.33890319e-314]],

       [[2.18480525e-314, 2.18480702e-314, 2.33751141e-314,
         2.18480525e-314, 2.18521437e-314],
        [2.18480702e-314, 2.33063134e-314, 2.18480525e-314,
         2.33063239e-314, 2.18510800e-314],
        [2.33063212e-314, 2.18480525e-314, 2.33063206e-314,
         2.18510800e-314, 2.33063209e-314],
        [2.18480525e-314, 2.33063223e-314, 2.18510800e-314,
         2.33063101e-314, 2.18480525e-314]],

       [[2.33616421e-314, 2.18480705e-314, 2.18510800e-314,
         2.18480702e-314, 2.33063176e-314],
        [2.18480525e-314, 2.33063195e-314, 2.18510800e-314,


In [19]:
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.arange(4)

array([0, 1, 2, 3])

In [21]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(3,10,2)

array([3, 5, 7, 9])

In [23]:
arreglo_pares = np.arange(0,20,2)

In [24]:
arreglo_pares.size

10

In [25]:
arreglo_pares.shape

(10,)

In [26]:
arreglo_pares.reshape((5,2))

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [27]:
np.arange(24).reshape((6,2,2))

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]]])

In [28]:
np.arange(100000)

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [30]:
np.arange(100000).reshape(10000,10)

array([[    0,     1,     2, ...,     7,     8,     9],
       [   10,    11,    12, ...,    17,    18,    19],
       [   20,    21,    22, ...,    27,    28,    29],
       ...,
       [99970, 99971, 99972, ..., 99977, 99978, 99979],
       [99980, 99981, 99982, ..., 99987, 99988, 99989],
       [99990, 99991, 99992, ..., 99997, 99998, 99999]])

In [31]:
a = np.array([10,10,10])

In [32]:
b = np.array([5,5,5])

In [33]:
#Suma
print(a+b)

[15 15 15]


In [34]:
#Resta
a-b

array([5, 5, 5])

In [35]:
#Multiplicación
a*b

array([50, 50, 50])

In [36]:
#División
a/b

array([2., 2., 2.])

In [37]:
#Módulo
a%b

array([0, 0, 0])

In [38]:
#Operaciones con enteros
a/2

array([5., 5., 5.])

In [39]:
a%2

array([0, 0, 0])

In [40]:
a+3

array([13, 13, 13])

In [41]:
a-2

array([8, 8, 8])

In [44]:
arreglo_doce = np.arange(12)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [43]:
arreglo_doce > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True])

In [46]:
A = np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [47]:
B = np.arange(4,8).reshape(2,2)
B

array([[4, 5],
       [6, 7]])

In [48]:
A + B

array([[ 4,  6],
       [ 8, 10]])

In [49]:
A - B

array([[-4, -4],
       [-4, -4]])

In [50]:
A * B

array([[ 0,  5],
       [12, 21]])

In [51]:
A / B

array([[0.        , 0.2       ],
       [0.33333333, 0.42857143]])

In [52]:
A % B

array([[0, 1],
       [2, 3]])

In [53]:
A.dot(B)

array([[ 6,  7],
       [26, 31]])

In [54]:
np.dot(A,B)

array([[ 6,  7],
       [26, 31]])

In [56]:
C = np.zeros_like(A)
C

array([[0, 0],
       [0, 0]])

In [57]:
RESULTADO = np.arange(4).reshape(2,2)
np.dot(A,B,RESULTADO)

array([[ 6,  7],
       [26, 31]])

In [59]:
arreglo_tres = np.arange(3)
arreglo_tres +=2
arreglo_tres

array([2, 3, 4])

In [60]:
arreglo_tres.sum()

9

In [61]:
arreglo_tres.min()

2

In [62]:
arreglo_tres.max()

4

In [68]:
arreglo_tres_cuatro = np.arange(24).reshape(6,2,2)
arreglo_tres_cuatro

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]]])

In [64]:
arreglo_tres_cuatro.sum()

66

In [69]:
#Suma de forma vertical
arreglo_tres_cuatro.sum(axis=1)

array([[ 2,  4],
       [10, 12],
       [18, 20],
       [26, 28],
       [34, 36],
       [42, 44]])

In [70]:
#Suma de forma horizontal
arreglo_tres_cuatro.sum(axis=0)

array([[60, 66],
       [72, 78]])

In [71]:
arreglo_tres_cuatro.sum(axis=2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21],
       [25, 29],
       [33, 37],
       [41, 45]])

In [72]:
arreglo_tres_cuatro.sum()

276